################################################################
# This is the PRODUCTION config file.
# 
# Run this command when ready to deploy/upload to your server:
# `jekyll build`
# 
# This file is *NOT* rebuilt automatically.
# If you change this file, please restart the server process
###############################################################

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

sass:
  style: compressed

highlighter: rouge

gems:
  - jekyll-seo-tag

include: ["_pages"] # custom directory to organize pages

permalink: /:title/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
